{% set name = "molscrub" %}
{% set version = "0.2.0" %}
{% set python_min = "3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/molscrub-{{ version }}.tar.gz
  sha256: 074c4c7f28fffe9e99695f99ab573d315f4b5ffdf3e70a248df46f96a182da3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - rdkit >=2022.03.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - scrubber
  commands:
    - scrub.py --help
    - pip check

about:
  home: https://github.com/forlilab/molscrub
  summary: 'Enumerate states of small organic molecules: 3D coordinates, tautomers, pH-based adjustments'
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joanimato
    - diogomart
